#+LATEX_CLASS: book
#+EXCLUDE_TAGS: noexport thesisnoexport
#+OPTIONS: tags:nil <:nil author:nil date:nil title:nil toc:nil


* Mapping on superconducting quantum processors

# Intro (Although the work done is general and it could serve to any quantum technology we will focus our studies in the SC-7 and SC-17 chips... -> Presentation of the chips)

In this chapter we describe the setup in which we focused on.
Although the work done is general and it could serve to any quantum technology we limit our studies on the SC-17 chip constrains.
We will explain the mapping model and the metrics used in the work.

** Constraints of the Surface-17 chip
:PROPERTIES:
:ID:       5fc58a48-9874-45ed-94ff-095153aeea0f
:END:

#+BEGIN_EXPORT latex
\subfile{chapters/constraints}
#+END_EXPORT

** Mapping model
:PROPERTIES:
:ID:       0a029c29-40ea-42ab-ad65-250a5a76bb49
:END:

#+INCLUDE: mapping_model.org

** New Mapping Metrics
:PROPERTIES:
:ID:       38ded492-56c6-4f6a-a629-06e342314cef
:END:

As mentioned in the [[id:e9551941-a680-421a-aecc-8b103368acd6][Mapping metrics]] section in the second chapter, we name /mapping metrics/ to those metrics used to assert the quality of a mapper and that are also used by the mapper algorithm as an heuristic.
In this section we will review the common metrics as the *number of SWAPs* or the *latency*, but we will also define -- and study in more detail -- some new mapping metrics that we incorporated, *probability of success* and *Quantum Volume*.

# *** Number of SWAPs

# #+INCLUDE: number_of_swaps.org

# *** Latency

# #+INCLUDE: latency.org

*** Probability of success and fidelity

#+INCLUDE: probability_of_success.org

*** Quantum Volume

#+INCLUDE: quantum_volume.org

