#+LATEX_CLASS: book
#+EXCLUDE_TAGS: noexport thesisnoexport
#+OPTIONS: tags:nil <:nil author:nil date:nil title:nil toc:nil
#  num:nil

* Results

In this chapter the simulation results are presented with reference to the aim of the thesis, which was to study the mapping metrics.
Their precision when assessing the mapping quality and their relation with the error amount after mapping.
First, in the [[id:96ce8da9-08d8-4fbb-9b15-8b044f01f1b7][Impact of mapping in the overall circuit error]] section we show how the mapping procedure affects the general increment of error.
After that, we analyze the metrics and their correlation with the error increase in the [[id:586ca325-54d8-4b90-93a0-1253140147c4][Analysis of the mapping metrics]] section.
Finally, in the [[id:5520e10c-045c-445a-a863-7eb221ad05c4][Advice]] section, after a regression study, we offer a way to predict the amount of errors a circuit could get depending on the its characteristics.

** Impact of mapping in the overall circuit error 
:PROPERTIES:
:ID:       96ce8da9-08d8-4fbb-9b15-8b044f01f1b7
:END:

#+INCLUDE: impact_of_mapping.org

** Analysis of the mapping metrics
:PROPERTIES:
:ID:       586ca325-54d8-4b90-93a0-1253140147c4
:END:

#+INCLUDE: metrics_analysis.org

** Advice
:PROPERTIES:
:ID:       5520e10c-045c-445a-a863-7eb221ad05c4
:END:

#+INCLUDE: regression.org
