
In addition to the general connectivity limitations, quantum devices -- no matter which technology -- are error prone.
Quantum operations are faulty and qubits are not able to hold the desired state for long times, gradually rotating to another state -- the qubit decoheres.
For instance, in the case of superconducting technologies cite:O_Brien_2017, the chips bear with decoherence times of $\approx 30 \mu s$ for qubit relaxation and $\approx 60 \mu s$ for qubit dephase.
The error rates of single-qubit gates are less than 0.1% taking $> 20 ns$ to be executed, while two-qubit gates error rate is 0.6% with times of $40 ns$ and measurement error rates around 1% with execution times of $\sim 300 ns$ cite:O_Brien_2017,Versluis_2017.
This creates an undesirable environment to compute the most useful algorithms.
Therefore, in order to fight the errors generated by this behaviour, fault-tolerant (FT) and quantum error correction (QEC) mechanisms have been developed during the last years cite:Nielsen_2009.
These techniques force the quantum chips layout to arrange the qubits in a particular manner, constraining them even more.

* BIB                                                       :ignore:noexport:

bibliography:../thesis_plan.bib
bibliographystyle:plain
