
In this section ...

*** Essential elements of quantum computation

Qubits and quantum gates are the basic ingredients in quantum computation theory.
As in classical computation with boolean gates and bits, quantum gates operate on the qubits to change their state and return the desired result or calculation.

**** Qubits

Qubit stands for quantum bit.
A basic unit of information founded on quantum physics laws.
Unlike a classical bit, whose state is either ~0~ or ~1~, but like a particle; qubits are not in a fixed state -- ground or excited -- until is measured.
A qubit's state could be either ~0~ or ~1~ or both before measuring it.
The ground or excited states are represented in the Dirac's bra-ket notation, viz. $| 0 \rangle$ and $| 1 \rangle$ respectively.
This notation holds the algebraic axioms required to understand the quantum theory.
Prior to measurement, a qubit is described as in a probabilistic state $| \Psi \rangle = \alpha | 0 \rangle + \beta | 1 \rangle$, where $\alpha, \beta \in \C$.
$\alpha$ is the probability of measuring $| 0 \rangle$, $\beta$ is the probability of measuring $| 1 \rangle$ and both are allowed to be complex.
As soon as they are energy probabilistic states, their values are constrained to $|\alpa|^2 + |\beta|^2$
The state is usually defined as a vector $\begin{bmatrix}\alpha \\ \beta \end{bmatrix}$.
Therefore, we can say that the state of a qubit is define by a 2-dimensional, complex and unitarian vector space.
E.g. ...

**** Quantum Gates
*** Quantum Circuits
